#R

# 2026.05.26
# Plot Figure 5 - Temporal Evolution of TTI with 95% CIs
# Uses pre-trained MLP70SPAT model and Elsevier formatting

library(torch)
library(terra)
library(dplyr)
library(ggplot2)
library(ggpubr) # For Elsevier publication theme

device <- ifelse(cuda_is_available(), "cuda", "cpu")
torch_device(device)
if (cuda_is_available()) { gc(); cuda_empty_cache() }

# --- 1. MODEL DEFINITION & LOADING ---
sim_name <- "Comprehensive"
model_name <- "MLP70SPAT"
run_date <- "2026-05-26"

# Make sure this points to the exact file generated by your training script
model_file_name <- paste0("./Models/", model_name, "_", sim_name,"_",run_date,".rt")

cat("Loading pre-trained model:", model_file_name, "\n")
model <- torch_load(model_file_name, device = device)
model$eval()

# --- 2. DATA LOADING & PREPARATION ---
rfile <- './GES_Baltic_5year_ALLE_Combined_4D.nc'
sds_input <- terra::sds(rfile, guessCRS=TRUE)

Depth_rast <- sds_input$Depth
ii.good <- which(!is.na(values(Depth_rast[[1]]))) 
ngoodp <- length(ii.good)
ntime <- 14
years <- seq(1955, 2020, by = 5)

cell_areas <- terra::cellSize(Depth_rast[[1]], unit="km")
water_areas <- values(cell_areas)[ii.good]

vari <- c("Nit", "Pho", "Chla", "DO2_mg", "Secchi", "Temp", "Depth")
target_var <- "TTI"

extracted_list <- list()
for (var_name in names(sds_input)) {
  extracted_list[[var_name]] <- as.vector(values(sds_input[[var_name]])[ii.good, ])
}
dataall <- as.data.frame(extracted_list)

for (p in vari) {
  dataall[[p]] <- scale(dataall[[p]])
}

# --- 3. FULL BASIN INFERENCE ---
cat("Generating ANN-TTI predictions...\n")
x_tensor <- torch_tensor(as.matrix(dataall[, vari]), dtype=torch_float(), device=device)

with_no_grad({
  ann_tti_raw <- as.numeric(model(x_tensor)$cpu())
})

true_tti_raw <- dataall[[target_var]]

# --- 4. CALCULATE SPATIAL MEANS & 95% CIs (FISHER Z-TRANSFORMED) ---
cat("Calculating area-weighted spatial means and Confidence Intervals...\n")
mean_true_tti <- numeric(ntime); lower_true_tti <- numeric(ntime); upper_true_tti <- numeric(ntime)
mean_ann_tti  <- numeric(ntime); lower_ann_tti  <- numeric(ntime); upper_ann_tti  <- numeric(ntime)

for (t in 1:ntime) {
  start_idx <- (t - 1) * ngoodp + 1
  end_idx   <- t * ngoodp
  
  slice_true <- true_tti_raw[start_idx:end_idx]
  slice_ann  <- ann_tti_raw[start_idx:end_idx]
  
  # Fisher z-transformation
  z_true <- atanh(pmin(pmax(slice_true, -0.999), 0.999))
  z_ann  <- atanh(pmin(pmax(slice_ann, -0.999), 0.999))
  
  # Area-weighted spatial mean of z-scores
  mean_z_true <- sum(z_true * water_areas) / sum(water_areas)
  mean_z_ann  <- sum(z_ann * water_areas) / sum(water_areas)
  
  # Weighted Variance and Standard Deviation
  w_sd_true <- sqrt(sum(water_areas * (z_true - mean_z_true)^2) / sum(water_areas))
  w_sd_ann  <- sqrt(sum(water_areas * (z_ann - mean_z_ann)^2) / sum(water_areas))
  
  # Standard Error of the Mean (SEM)
  # NOTE: To plot Spatial Standard Deviation (regional spread) instead of SEM, 
  # simply change the two lines below to: se_true <- w_sd_true
  se_true <- w_sd_true #/ sqrt(ngoodp)
  se_ann  <- w_sd_ann # / sqrt(ngoodp)
  
  # 95% CI bounds in z-space
  fac95 = 1.96
  fac95 = 1.0
  z_lower_true <- mean_z_true - (fac95 * se_true)
  z_upper_true <- mean_z_true + (fac95 * se_true)
  
  z_lower_ann <- mean_z_ann - (fac95 * se_ann)
  z_upper_ann <- mean_z_ann + (fac95 * se_ann)
  
  # Inverse transformation back to TTI space
  mean_true_tti[t] <- tanh(mean_z_true)
  lower_true_tti[t] <- tanh(z_lower_true)
  upper_true_tti[t] <- tanh(z_upper_true)
  
  mean_ann_tti[t]  <- tanh(mean_z_ann)
  lower_ann_tti[t] <- tanh(z_lower_ann)
  upper_ann_tti[t] <- tanh(z_upper_ann)
}

# --- 5. PUBLICATION-READY GGPLOT2 TIME SERIES ---
# Compile into a long format data frame suitable for ggplot grouping
plot_df <- rbind(
  data.frame(Year = years, Model = "Ecosystem Model (True TTI)", 
             Mean_TTI = mean_true_tti, Lower = lower_true_tti, Upper = upper_true_tti),
  data.frame(Year = years, Model = paste0(model_name, " (Predicted TTI)"), 
             Mean_TTI = mean_ann_tti, Lower = lower_ann_tti, Upper = upper_ann_tti)
)

p_ts <- ggplot(plot_df, aes(x = Year, y = Mean_TTI, color = Model, shape = Model, linetype = Model)) +
  
  geom_hline(yintercept = 0.71, color = "grey40", linetype = "dashed", linewidth = 1) +
  #annotate("text", x = 1985, y = 0.72, label = "GES Threshold (0.71)", color = "grey40", fontface = "bold", size = 4) +
  ## ylim(0.4,0.9) +
  # Add the 95% CI Error Bars
  geom_errorbar(aes(ymin = Lower, ymax = Upper), width = 1.2, linewidth = 0.6, 
                position = position_dodge(width = 0.7)) +
  
  geom_line(linewidth = 1.2, position = position_dodge(width = 0.5)) +
  geom_point(size = 3.5, fill = "white", stroke = 1.5, position = position_dodge(width = 0.5)) +
  
  scale_color_manual(values = c("Ecosystem Model (True TTI)" = "black", 
                                "MLP70SPAT (Predicted TTI)" = "#d95f02")) +
  scale_shape_manual(values = c(16, 21)) +
  scale_linetype_manual(values = c("solid", "solid")) +
  
  scale_x_continuous(breaks = seq(1955, 2020, by = 5), expand = c(0.02, 0.02)) +
  
  labs(
    title = "Temporal Evolution of Mean Trophic Transfer Index",
    subtitle = "Area-weighted spatial means. Dashed line indicates TTI-GES Threshold (0.71).",
    x = "Assessment Year (Pentad Center)",
    #y = "Area-Weighted Mean TTI ± 95% CI",
    y = "Area-Weighted Mean TTI ± SD",
    color = NULL, shape = NULL, linetype = NULL
  ) +
  
  theme_pubr(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5, size = 16, margin = margin(b = 15)),
    legend.position = "bottom",
    legend.text = element_text(size = 12, face = "bold"),
    legend.background = element_rect(fill = NA, color = NA),
    legend.margin = margin(t = 5),
    panel.grid.major = element_line(color = "grey85"),
    axis.title = element_text(face = "bold", size = 14),
    axis.text = element_text(color = "black", size = 12)
  )

print(p_ts)

ggsave(paste0("Figure5_Temporal_TTI_Comparison_", sim_name, "_Elsevier.png"), 
       plot = p_ts, 
       width = 7.48, height = 5.5, dpi = 500, bg = "white")


message("Elsevier-compliant time series plot successfully generated and saved.")

